name: "Release next full version from release branch"

on:
  schedule:
    - cron: '0 0 * * 1'

run-name: Release next full version to pypi and github
jobs:
  get_tag_name:
    name: Calculate next RC number
    env:
      CURRENT_BRANCH: ${{ github.ref_name }}
    runs-on: ubuntu-latest
    outputs:
      next_version: ${{ steps.calculate-next-version.outputs.next_version }}
    steps:
      - name: Get latest RC tag
        id: latest_rc_tag
        uses: oprypin/find-latest-tag@v1
        with:
          repository: man-group/ArcticDB
          regex: ^v\d+\.\d+\.\d+rc\d+$
      
      - name: Calculate next version
        id: calculate-next-version
        run: |
          CURRENT_BRANCH="${{ github.ref_name }}"
          LATEST_TAG="${{ steps.latest_rc_tag.outputs.tag }}"
          LATEST_TAG="${LATEST_TAG#v}"
          base="${LATEST_TAG%rc*}"
          echo "next_version=$base" >> $GITHUB_OUTPUT

  tag_and_release:
    name: Tag and release version ${{ needs.get_tag_name.outputs.next_version }} 
    uses: ./.github/workflows/tag.yml
    needs: get_tag_name
    with:
      version: ${{ needs.get_tag_name.outputs.next_version }}  
      from_branch: ${{ github.ref_name }}