name: "Release next RC from release branch"

on:
  push:
    branches:
      - '[0-9]+.[0-9]+.[0-9]'
  workflow_call:
    inputs:
      branch_name: 
        type: string
        required: true
  schedule:
    - cron: '0 0 * * *'  # Runs every day at midnight UTC
    
      

jobs:
  get_tag_name:
    name: Calculate next RC number
    env:
      CURRENT_BRACH: ${{ inputs.branch_name || github.ref_name }}
    runs-on: ubuntu-latest
    outputs:
      next_version: ${{ steps.latest_rc_tag.outputs.next_version || steps.latest_tag.outputs.next_version }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 

      - name: Find latest RC tag and increment
        id: latest_rc_tag
        if: ${{ github.event_name != 'schedule' }}
        run: |
          TAG=v${{ env.CURRENT_BRACH }}
          echo "Getting tag for $TAG"
          LATEST_TAG=$(git tag -l "${TAG}rc*" | sort -V | tail -n 1)
          if [[ -z "$LATEST_TAG" ]]; then
            NEXT_RC=0
          else
            NEXT_RC=$(( ${LATEST_TAG##*rc} + 1 ))
          fi
          NEXT_TAG=${TAG}rc${NEXT_RC}
          echo "Latest tag is $LATEST_TAG"
          echo "Next tag is $NEXT_TAG"
          echo "next_version=${NEXT_TAG#v}" >> $GITHUB_OUTPUT
      - uses: InsonusK/get-latest-release@v1.0.1
        id: get-latest-release
        with:
          myToken: ${{ github.token }}
          exclude_types: "prerelease|draft"
          view_top: 10 
      - name: Find tag name for release
        id: latest_tag
        if: ${{ github.event_name == 'schedule' }}
        run: |
          echo "created_at: ${{ steps.last_release.outputs.created_at }}"
          echo "next_version=v${{ env.CURRENT_BRACH }}" >> $GITHUB_OUTPUT

  tag_and_release:
    uses: ./.github/workflows/tag.yml
    needs: get_tag_name
    with:
      version: ${{ needs.get_tag_name.outputs.next_version }}  
